appdelta/urls.py
from django.conf.urls import patterns, url
from appdelta.views import *

urlpatterns = patterns('',
    url(r'^index', Viewindex.as_view(), name='index'),
    url(r'^agregarclientes', Viewagregar.as_view(), name='agregarclientes'),
    url(r'^admin', Viewadmin.as_view(), name='admin'),
    url(r'^login', Viewlogin.as_view(), name='login'),
    url(r'^cerrarseccion', Viewcerrar.as_view(), name='cerrarseccion'),
    url(r'^inicio', Viewinicio.as_view(), name='inicio'),
    url(r'^informacion', Viewinformacion.as_view(), name='informacion'),
    url(r'^(?P<pk>\d+)/cambiarpassword/$', Vieweditar.as_view(), name="cambiarpassword"),    
    #url(r'^(?P<pk>\d+)/login/$', Viewlogin.as_view(), name="login"),
    url(r'^(?P<pk>\d+)/editarclientes/$', Vieweditar.as_view(), name="editarclientes"),
    url(r'^(?P<pk>\d+)/abono/$', Viewabono.as_view(), name="abono"),
    url(r'^(?P<pk>\d+)/verabonos/$', Viewmirar.as_view(), name="verabonos"),
    url(r'^(?P<pk>\d+)/admincliente/$', Viewadcliente.as_view(), name='admincliente'),
)

proyecto_delta/urls.py
from django.conf.urls import url
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appdelta/', include('appdelta.urls', namespace='appdelta', app_name='appdelta')),
    url(r'', include('appdelta.urls', namespace='appdelta', app_name='appdelta')),
]

appdelta/forms.py
from django import forms
from .models import datos_cliente
from .models import prestamo_cliente
from .models import login_admin

class PostForm(forms.ModelForm):

        class Meta:
            
            model = datos_cliente
            exclude = ['total_payment','deuda_actual','payment','total_abonado','date','presmaspor','dateprestamo','datelimite']

            widgets = {
                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'document': forms.TextInput(attrs={'class': 'form-control'}),
                'Address': forms.TextInput(attrs={'class': 'form-control'}),
                'trade': forms.TextInput(attrs={'class': 'form-control'}),
                'loan': forms.TextInput(attrs={'class': 'form-control'}),
                'payment_days': forms.TextInput(attrs={'class': 'form-control'}),
                'percent': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Porcentaje'}),
                'phone': forms.TextInput(attrs={'class': 'form-control'}),                
                'total_payment': forms.TextInput(attrs={'class': 'form-control'}),
                'deuda_actual': forms.TextInput(attrs={'class': 'form-control'}),
            }


class AdminForm(forms.ModelForm):
    
        class Meta:
            
            model = prestamo_cliente
            exclude = ['documen','sumado','deuda_actual','payment_total','date','total_payment','total_abonado','hour','total_abonado_dia','dateprestamo','datelimite']
            
            widgets = {
               'date': forms.TextInput(attrs={'class': 'form-control'}),               
               'total_days': forms.TextInput(attrs={'class': 'form-control'}),
               'total_payment': forms.TextInput(attrs={'class': 'form-control'}),
               'delayed_days': forms.TextInput(attrs={'class': 'form-control'}),
               'payment': forms.TextInput(attrs={'class': 'form-control'}),
               'sumado': forms.TextInput(attrs={'class': 'form-control'}),
               'deuda_actual': forms.TextInput(attrs={'class': 'form-control'}),
            }
            
            
class AbonoForm(forms.ModelForm):
    
        class Meta:
            
            model = datos_cliente
            exclude = ['trade','name','Address','loan','payment_days','percent','phone','total_payment','deuda_actual','payment_total','hour','total_abonado_dia',]
            
            widgets = {
                'nombre': forms.TextInput(attrs={'class': 'form-control'}),
                'document': forms.TextInput(attrs={'class': 'form-control'}),
                'payment': forms.TextInput(attrs={'class': 'form-control'}),
                #'payment_total': forms.TextInput(attrs={'class': 'form-control'}),
            }
            
            
class EditForm(forms.ModelForm):
    
    class Meta:
            
            model = datos_cliente
            exclude = ['total_payment','deuda_actual','payment','document','loan','percent','payment_days','total_abonado','date','presmaspor','dateprestamo','datelimite']
    
            widgets = {
                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'Address': forms.TextInput(attrs={'class': 'form-control'}),
                'trade': forms.TextInput(attrs={'class': 'form-control'}),
                'phone': forms.TextInput(attrs={'class': 'form-control'}),
                'dateprestamo': forms.TextInput(attrs={'class': 'form-control'}), 
            }


class LoginForm(forms.ModelForm):
    
    class Meta:
            
            model = login_admin
            exclude = ['name','permisos','cargo','passw']
    
            widgets = {
                'customers': forms.TextInput(attrs={'class': 'form-control'}),
                'password': forms.TextInput(attrs={'class': 'form-control', 'type':'password'}),             
            }

           
class PasswForm(forms.ModelForm):
    
    class Meta:
            
            model = login_admin
            exclude = ['name','permisos','cargo','customers']
    
            widgets = {
                'password': forms.TextInput(attrs={'class': 'form-control', 'type':'password'}),             
            }
            
            
class DiaForm(forms.ModelForm):
    
    class Meta:
            
            model = login_admin
            exclude = ['date','abono_diario']
    
            widgets = {}


appdelta/views.py
# -*- coding: utf8 -*-
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, render
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.contrib import messages
from appdelta.models import *
from appdelta.forms import *
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, timedelta
from django.template import RequestContext
from django.db.models import Q
# Create your views here.

class Viewindex(View):    
    
    template_name = 'index.html'
        
    def get(self, request, *args, **kwargs):
        if request.session['acceso'] == True:
            print(request.session['acceso'])
            Datos_cliente = datos_cliente.objects.all()
            
            query = request.GET.get('q', '')
            
            if query:
                qset = (
                    Q(name__icontains=query) |
                    Q(document__icontains=query) 
                )
                results = datos_cliente.objects.filter(qset).distinct()
            else:
                results = []
                
            return render(request, self.template_name, {
                "Datos_cliente": Datos_cliente,
                "results": results,
                "query": query
            })
        else:
            return HttpResponseRedirect(reverse('appdelta:login'))   


class Viewadmin(View):
    
    template_name = 'admin.html' 
    
    def get(self, request, *args, **kwargs):
        
        if request.session['acceso'] == True:
            Datos_cliente = datos_cliente.objects.all()
            query = request.GET.get('q', '')
            
            if query:
                qset = (
                    Q(name__icontains=query) |
                    Q(document__icontains=query) 
                )
                results = datos_cliente.objects.filter(qset).distinct()
            else:
                results = []            
            return render_to_response(self.template_name, {
                "Datos_cliente": Datos_cliente,
                "results": results,
                "query": query
            })
        else:
            return HttpResponseRedirect(reverse('appdelta:login'))
       
       
class Viewagregar(View):

    template_name = 'agregarclientes.html'     
        
    def get(self, request, *args, **kwargs): 
        if request.session['acceso'] == True:
            form = PostForm()
            return render(request, self.template_name, {
                    'form': form,
                })
        else:
            return HttpResponseRedirect(reverse('appdelta:login'))
         
    def post(self, request, *args, **kwargs):
        datos = datos_cliente.objects.all()
        form = PostForm(request.POST)
        
        if request.POST.get('save'):
                       
            if form.is_valid():
                
                appdelta = form.save(commit=False)
                appdelta.total_payment = (appdelta.percent/100) * appdelta.loan + appdelta.loan
                appdelta.deuda_actual = (appdelta.percent/100) * appdelta.loan + appdelta.loan
                appdelta.total_abonado = 0
                appdelta.presmaspor = 0
                appdelta.presmaspor = appdelta.loan + (appdelta.loan * appdelta.percent/100)
                
                appdelta.date = datetime.now().strftime("%Y/%m/%d")             
                
                appdelta.datelimite = datetime.now()+timedelta(days=appdelta.payment_days)
                appdelta.datelimite= appdelta.datelimite.strftime("%Y/%m/%d")
                
                appdelta.save()
                print('hola')
                return HttpResponseRedirect(reverse('appdelta:agregarclientes'))
            else:
                return render(request, self.template_name, {
                    'form': form,
            })


class Viewabono(View):
    
    template_name = 'abono.html'
    
    def get(self, request, *args, **kwargs):
        if request.session['acceso'] == True:
            Datos_cliente = datos_cliente.objects.get(pk=kwargs['pk'])
            form = AbonoForm(instance=Datos_cliente)
            return render(request, self.template_name, {
                'form': form,
            })
        else:
            return HttpResponseRedirect(reverse('appdelta:login'))
        
    def post(self, request, *args, **kwargs):
        Datos_cliente = datos_cliente.objects.get(pk=kwargs['pk']) 
        form = AbonoForm(request.POST, instance=Datos_cliente)
        
        if request.POST.get('saveabono'):
            if form.is_valid():
                Datos_cliente = form.save(commit=False)
                Datos_cliente.deuda_actual = Datos_cliente.deuda_actual - Datos_cliente.payment
                Datos_cliente.save()
                return HttpResponseRedirect(reverse('appdelta:index'))
            else:
                return render(request, self.template_name, {
                    'form': form,
    })


class Vieweditar(View):
    
    template_name = 'editarclientes.html'
    
    def get(self, request, *args, **kwargs):
        if request.session['acceso'] == True:
            Datos_cliente = datos_cliente.objects.get(pk=kwargs['pk'])
            form = EditForm(instance=Datos_cliente)
            return render(request, self.template_name, {
                'form': form,
            })
        else:
            return HttpResponseRedirect(reverse('appdelta:login'))
        
    def post(self, request, *args, **kwargs):
        Datos_cliente = datos_cliente.objects.get(pk=kwargs['pk']) 
        form = EditForm(request.POST, instance=Datos_cliente)
        
        if request.POST.get('saveedit'):
            if form.is_valid():
                Datos_cliente = form.save()
                return HttpResponseRedirect(reverse('appdelta:index'))
            else:
                return render(request, self.template_name, {
                    'form': form,
    })            
    
    
class Viewadcliente(View):
    
    template_name = 'admincliente.html'
    
    def get(self, request, *args, **kwargs):
        if request.session['acceso'] == True:
            datos = datos_cliente.objects.get(pk=kwargs['pk'])
            fecha = datetime.now().strftime("%Y/%m/%d")
            prestamo = prestamo_cliente.objects.all()
            form = AdminForm
            return render(request, self.template_name, {'form': form, 'datos': datos, })
        else:
            return HttpResponseRedirect(reverse('appdelta:login'))
    
    def post(self, request, *args, **kwargs):
        try:

            prestamo = prestamo_cliente.objects.all()
            abono_dia = 0
            fecha = datetime.now().strftime("%Y/%m/%d")
            datos = datos_cliente.objects.get(pk=kwargs['pk'])                      
            form = AdminForm(request.POST)
            if request.POST.get('savepres'):
                if form.is_valid():
                    appdelta = form.save(commit=False)
                    print(appdelta.total_payment)

                    if datos.total_payment == None:
                        datos.total_payment = 0
                    else:
                        datos.total_payment = datos.total_payment - appdelta.payment
                        appdelta.total_payment = datos.total_payment
                        print(datos.total_payment)

                    if datos.total_abonado == None:
                        datos.total_abonado = 0
                        datos.total_abonado = datos.total_abonado + appdelta.payment
                        appdelta.total_abonado = datos.total_abonado
                    else:
                        datos.total_abonado = datos.total_abonado + appdelta.payment
                        appdelta.total_abonado = datos.total_abonado                     
                    
                    if datos.presmaspor == None:
                        datos.presmaspor = 0
                        datos.presmaspor = datos.loan + (datos.loan * datos.percent/100)
                    
                    if datos.total_abonado == None:
                        datos.total_abonado = 0
                    
                    
                    appdelta.documen = datos
                    appdelta.date = datetime.now().strftime("%Y/%m/%d")
                    appdelta.hour = datetime.now().strftime("%H:%M")                
                    datos.save()
                    appdelta.save()
                    return HttpResponseRedirect(reverse('appdelta:admin'))            
                else:
                    return render(request, self.template_name, {'form': form, 'datos': datos,})            
        except ObjectDoesNotExist:
            raise Htpp404("No existe la cuenta")
        

class Viewmirar(View):
    
    template_name = 'verabonos.html'
    
    def get(self, request, *args, **kwargs):
        if request.session['acceso'] == True:
            prestamo = prestamo_cliente.objects.all().filter(documen = kwargs["pk"])        
            form = AbonoForm(request.GET)        
            return render(request, self.template_name, {
                'prestamo': prestamo,
            })
        else:
            return HttpResponseRedirect(reverse('appdelta:login'))
        

class Viewlogin(View):
    
    template_name = 'login.html'
    def get(self, request, *args, **kwargs):
        login = login_admin.objects.all()
        form = LoginForm(request.GET)
        return render(request, self.template_name, {'form': form, 'login': login,})
    
    def post(self, request, *args, **kwargs):
        
        if request.POST.get('press'):
            
            form = LoginForm(request.POST)
            login = login_admin.objects.all()
            if form.is_valid(): 
                appdelta = form.save(commit=False)
                for log in login:

appdelta/templates/abono.html
{% extends "deltamaster.html" %}
{% load widget_tweaks %}
{% block content %}

--ELIMINAR--

<form action="{% url 'appdelta:editarclientes' form.instance.document %}" method="post">	
 		{% csrf_token %}
 	
		{% for error in field.errors %}
			<li>{{ error }}</li>
		{% endfor %}
		
	<div class="container-fluid col-md-4 col-md-offset-3">
		<div class="jumbotron">
			<h2 align="center"><b>Abono Clientes</b></h2>
			
		</div>
		
		<div class="container">
			<a href="{% url 'appdelta:index' %}"><h4 align="center"><b>Volver</b></h4></a><br />
		</div>
		
		{% for field in form %}
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
				<label>{{ field.label }}</label>
					{{ field }}
				&nbsp;<div>{{ field.document }}</div>
				</div>
			</div>
		{% endfor %}
		<br/>
		<div class="container">
			<div class="col-md-6 col-md-offset-3" align="center">
				<input type="submit" name="saveabono" id="saveabono" value="Guardar" class="btn btn-primary btn-lg btn-block">
			</div>+
		</div>
		
	</div>
		
	
</form>

{% endblock %}

appdelta/templates/addprestamos.html
{% extends "deltamaster.html" %}
{% load widget_tweaks %}
{% block content %}

--ELIMINAR--

<form action="{% url 'appdelta:addprestamos' datos.document %}" method="post" >{% csrf_token %}
	{% csrf_token %}
	{% for field in form %}
		<div>
		
			<label>hola esto si funciona</label>

			<label>{{ field.label }}</label>
			<div>{{ field }}</div>			
			<div>{{ field.errors }}</div>
		</div>
	{% endfor %}
	<br />	
	<input type="submit" name="savepres" id="savepres" value="Guardar" class="btn btn-primary btn-lg btn-block">
</form>

{% endblock %}

appdelta/templates/admin.html
{% extends "deltamaster.html" %}
{% load widget_tweaks %}
{% block content %}

<form action="{% url 'appdelta:admin' %}">

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 align="center">Buscar clientes</h4>		
		</div>		
		<br/>	
		<div class="panel-body">
		
		<form action="." method="GET">
		    <label for="q"></label>
		    <input class="form-control" placeholder="Busqueda" type="text" name="q" value="{{ query|escape }}">
		    <br/>
		    <input type="submit" name="button" id="button" value="Buscar" class="btn btn-primary btn-block">
	  	</form>
	  	
	  		{% if query %}
    			<h4>Resultados para: {{ query|escape }}</h4>
    		
		
			{% if results %}
			
			<div class="table-responsive">
				<table class="table table-bordered table-striped ">
					<thead>
						<tr>
							<th>Abonar</th>
							<th>Ver</th>
							<th>Nombre</th>
							<th>Documento</th>
							<th>Negocio</th>
							<th>Total abonado</th>
							<th>Total a pagar</th>
							<th>Fecha del prestamo</th>							
						</tr>
					</thead>
					<tbody>
						{% for resl in results %}
							<tr>			
								<td align="center">
									<div>
										<a href="{% url 'appdelta:admincliente' resl.document %}">
											<button class="btn btn-default" type="button" value="Editar">
												 <span class="glyphicon glyphicon-book" aria-hidden="true">
												 </span>
											</button>
										</a>
									</div>
								</td>
								<td align="center">
									<div>
										<a href="{% url 'appdelta:verabonos' resl.document %}">
											<button class="btn btn-default" type="button" value="Editar">
												 <span class="glyphicon glyphicon-book" aria-hidden="true">
												 </span>
											</button>
										</a>
									</div>
								</td>			
								<td>{{ resl.name }}</td>
								<td>{{ resl.document }}</td>
								<td>{{ resl.trade }}</td>
								<td>{{ resl.total_abonado }}</td>
								<td>{{ resl.total_payment }}</td>								
								<td>{{ resl.date }}</td>					
							</tr>
						{% endfor %}
					</tbody>
				</table>
				
				{% endif %}
				{% endif %}
				
			</div>
		</div>		
	</div>	
</div>

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 align="center">Tabla clientes</h4>		
		</div>		
		<div class="panel-body">
			
		<div class="table-responsive">
				<table class="table table-bordered table-striped ">
					<thead>
						<tr>
							<th>Abonar</th>
							<th>Ver</th>
							<th>Nombre</th>
							<th>Documento</th>
							<th>Negocio</th>
							<th>Total abonado</th>
							<th>Total a pagar</th>
							<th>Fecha del prestamo</th>
						</tr>
					</thead>
					<tbody>
						{% for datos in Datos_cliente %}
							<tr>
								<td align="center">
									<div>
										<a href="{% url 'appdelta:admincliente' datos.document %}">
											<button class="btn btn-default" type="button" value="Editar">
												 <span class="glyphicon glyphicon-book" aria-hidden="true">
												 </span>
											</button>
										</a>
									</div>
								</td>
								<td align="center">
									<div>
										<a href="{% url 'appdelta:verabonos' datos.document %}">
											<button class="btn btn-default" type="button" value="Editar">
												 <span class="glyphicon glyphicon-book" aria-hidden="true">
												 </span>
											</button>
										</a>
									</div>
								</td>					
								<td>{{ datos.name }}</td>
								<td>{{ datos.document }}</td>
								<td>{{ datos.trade }}</td>
								<td>{{ datos.total_abonado }}</td>
								<td>{{ datos.total_payment }}</td>
								<td>{{ datos.date }}</td>														
							</tr>
						{% endfor %}
					</tbody>
				</table>			
			</div>	
		</div>
	</div>
</div>

</form>

{% endblock %}

appdelta/templates/admincliente.html
{% extends "deltamaster.html" %}
{% load widget_tweaks %}
{% block content %}

<form action="{% url 'appdelta:admincliente' datos.document %}" method="post">{% csrf_token %} 
	{% csrf_token %} 		
	{% for error in field.errors %}
		<li>{{ error }}</li>
	{% endfor %}
	
	<div class="container-fluid col-md-4 col-md-offset-4">
		<div class="container">
			<a href="{% url 'appdelta:admin' %}"><h5 align="left"><b>Atras</b></h5></a><br />
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 align="center"><b>Abonar</b></h4>					
			</div>	
			<br/>
			<div class="panel-body">
				{% for field in form %}
					<div>
						<label>{{ field.label }}</label>
						<div>{{ field }}</div>			
						<div>{{ field.errors }}</div>
					</div>					
				{% endfor %}
				<br />	
				<input type="submit" name="savepres" id="savepres" value="Guardar" class="btn btn-primary btn-block" />
			</div>
		</div>
	</div>	
	
</form>

{% endblock %}

appdelta/templates/agregarclientes.html
{% extends "deltamaster.html" %}
{% load widget_tweaks %}
{% block content %}

<form method="post" action="{% url 'appdelta:agregarclientes' %}">{% csrf_token %}

		{% csrf_token %}
 		
		{% for error in field.errors %}
			<li>{{ error }}</li>
		{% endfor %}
		
	<div class="container-fluid col-md-6 col-md-offset-3">
		<div class="container">
			<a href="{% url 'appdelta:inicio' %}"><h5 align="left"><b>Atras</b></h5></a><br />
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 align="center"><b>Agregar Cliente</b></h4>					
			</div>
			
			</br>
			
			<div class="row">
				<div class="col-sm-1"></div>
		    	{% include "register/field.html" with field=form.name row_size=5 %}&nbsp;
		    	{% include "register/field.html" with field=form.document row_size=5 %}	     				
		    </div>
		    
		    <br/>
		    
		    <div class="row">
				<div class="col-sm-1"></div>
		    	{% include "register/field.html" with field=form.Address row_size=5 %}&nbsp;
		    	{% include "register/field.html" with field=form.trade row_size=5 %}	 				
		    </div>
		    
		    <br/>
		    
		    <div class="row">
				<div class="col-sm-1"></div>
		    	{% include "register/field.html" with field=form.loan row_size=5 %}&nbsp;
		    	{% include "register/field.html" with field=form.payment_days row_size=5 %}	 				
		    </div>
		    
		    <br/>
		    
		    <div class="row">
				<div class="col-sm-1"></div>
				{% include "register/field.html" with field=form.phone row_size=5 %}&nbsp;
				{% include "register/field.html" with field=form.dateprestamo row_size=5 %}			
			</div>	   
				    
			<br/>
			
		    <div class=row>
			    <div class="container">				    	
			    	<div class="input-group col-md-4 col-md-offset-1"><label>Porcentaje</label></div>
				    <div class="input-group col-md-4 col-md-offset-1" >
				    	{{ form.percent}}			      
				    	<div class="input-group-addon">%</div>
				    </div>
				    
				    <br/>	 	
				    				    	 
				</div>
			</div>
			
			<br/>
			<br/>
		    
		    <div class="container">
			    <div class="col-md-6 col-md-offset-3" align="center">	
			    	<input type="submit" name="save" id="save" value="Guardar" class="btn btn-primary btn-lg btn-block">
			    </div>	
		    </div>
		    
		    <br/>
		    <br/>
		    
		</div>
			
	</div>
</form>


{% endblock %}

appdelta/templates/cerrarseccion.html
{% extends "deltamaster.html" %}
{% load widget_tweaks %}
{% block content %}

{% endblock %}

appdelta/templates/editarclientes.html
{% extends "deltamaster.html" %}
{% load widget_tweaks %}
{% block content %}

 	
<form action="{% url 'appdelta:editarclientes' form.instance.document %}" method="post">	
 		{% csrf_token %}
 	
		{% for error in field.errors %}
			<li>{{ error }}</li>
		{% endfor %}
	<div class="col-md-6 col-md-offset-3">
		<div class="container">
			<a href="{% url 'appdelta:index' %}"><h5 align="left"><b>Atras</b></h5></a><br />
		</div>
		
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 align="center"><b>Editar Clientes</b></h4>					
			</div>	
		</br>
		{% for field in form %}
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
				<label>{{ field.label }}</label>
					{{ field }}
				&nbsp;<div>{{ field.document }}</div>
				</div>
			</div>
		{% endfor %}
		<br/>
		<div class="">
			<div class="col-md-8 col-md-offset-2">
				<input type="submit" name="saveedit" id="saveedit" value="Guardar" class="btn btn-primary btn-block">
			</div>
			</br>
		</div>
		
	</div>
	</div>
		
	
</form>


{% endblock %}

appdelta/templates/index.html
{% extends "deltamaster.html" %}
{% load widget_tweaks %}
{% block content %}	
	

<form action="{% url 'appdelta:index' %}">	

<div class="container">

	<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 align="center">Buscar clientes</h4>		
		</div>		
		<br/>	
		<div class="panel-body">
		
		<form action="." method="GET">
		    <label for="q"></label>
		    <input class="form-control" placeholder="Busqueda" type="text" name="q" value="{{ query|escape }}">
		    <br/>
		    <input type="submit" name="button" id="button" value="Buscar" class="btn btn-primary btn-block">
	  	</form>
	  	
	  		{% if query %}
    			<h4>Resultados para: {{ query|escape }}</h4>
    		
		
			{% if results %}
			
			<div class="table-responsive">
				<table class="table table-bordered table-striped ">
					<thead>
						<tr>
							<th>editar</th>
							<th>Nombre</th>
							<th>Documento</th>
							<th>Negocio</th>
							<th>Dirección</th>
							<th>Telefono</th>							
						</tr>
					</thead>
					<tbody>
						{% for resl in results %}
							<tr>			
								<td align="center">
									<div>
										<a href="{% url 'appdelta:editarclientes' resl.document %}">
											<button class="btn btn-default" type="button" value="Editar">
												 <span class="glyphicon glyphicon-pencil" aria-hidden="true">
												 </span>
											</button>
										</a>
									</div>
								</td>			
								<td>{{ resl.name }}</td>
								<td>{{ resl.document }}</td>
								<td>{{ resl.trade }}</td>
								<td>{{ resl.Address }}</td>
								<td>{{ resl.phone }}</td>												
							</tr>
						{% endfor %}
					</tbody>
				</table>
				
				{% endif %}
				{% endif %}
				
			</div>
		</div>		
	</div>	
</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<h4 align="center">Editar clientes</h4>		
		</div>		
		<br/>
		<div class="panel-body">
			<div class="table-responsive">
				<table class="table table-bordered table-striped ">
					<thead>
						<tr>
							<th>editar</th>
							<th>Nombre</th>
							<th>Documento</th>
							<th>Negocio</th>
							<th>Dirección</th>
							<th>Telefono</th>							
						</tr>
					</thead>
					<tbody>
						{% for datos in Datos_cliente %}
							<tr>
								<td align="center">
									<div>
										<a href="{% url 'appdelta:editarclientes' datos.document %}">
											<button class="btn btn-default" type="button" value="Editar">
												 <span class="glyphicon glyphicon-pencil" aria-hidden="true">
												 </span>
											</button>
										</a>
									</div>
								</td>							
								<td>{{ datos.name }}</td>
								<td>{{ datos.document }}</td>
								<td>{{ datos.Address }}</td>
								<td>{{ datos.trade }}</td>
								<td>{{ datos.phone }}</td>																					
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>	
</div>

</form>

{% endblock %}