appdelta/urls.py
from django.conf.urls import patterns, url
from appdelta.views import *

urlpatterns = patterns('',
    url(r'^index', Viewindex.as_view(), name='index'),
    url(r'^agregarclientes', Viewagregar.as_view(), name='agregarclientes'),
    url(r'^admin', Viewadmin.as_view(), name='admin'),
    url(r'^login', Viewlogin.as_view(), name='login'),
    url(r'^cerrarseccion', Viewcerrar.as_view(), name='cerrarseccion'),
    url(r'^inicio', Viewinicio.as_view(), name='inicio'),
    url(r'^informacion', Viewinformacion.as_view(), name='informacion'),
    url(r'^(?P<pk>\d+)/cambiarpassword/$', Vieweditar.as_view(), name="cambiarpassword"),    
    #url(r'^(?P<pk>\d+)/login/$', Viewlogin.as_view(), name="login"),
    url(r'^(?P<pk>\d+)/editarclientes/$', Vieweditar.as_view(), name="editarclientes"),
    url(r'^(?P<pk>\d+)/abono/$', Viewabono.as_view(), name="abono"),
    url(r'^(?P<pk>\d+)/verabonos/$', Viewmirar.as_view(), name="verabonos"),
    url(r'^(?P<pk>\d+)/admincliente/$', Viewadcliente.as_view(), name='admincliente'),
)

proyecto_delta/urls.py
from django.conf.urls import url
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appdelta/', include('appdelta.urls', namespace='appdelta', app_name='appdelta')),
    url(r'', include('appdelta.urls', namespace='appdelta', app_name='appdelta')),
]

templates/bootstrapmaster.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<html lang="es">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilosdelta.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-responsive.min.css' %}" />
	
	<script src="{% static "js/jquery.js" %}"></script>
	<script src="{% static "js/jquery-1.10.2.js" %}"></script>
	<script src="{% static "js/bootstrap.js" %}"></script>
	
</head>

<body>
	
	<div>	
		
		{% block content %}
		{% endblock %}  
		  	   
	</div>
	
</body>

</html>

templates/deltamaster.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<html lang="es">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/estilosdelta.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-responsive.min.css' %}" />
	
	<script src="{% static "js/jquery.js" %}"></script>
	<script src="{% static "js/jquery-1.10.2.js" %}"></script>
	<script src="{% static "js/bootstrap.js" %}"></script>
	
</head>

<body>
	
<div>
	
	<nav class="hello navbar navbar-inverse navbar-static-top">
	  <div class="">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'appdelta:inicio' %}"><font color="white">&nbsp;Prestamos Delta</font></a>
	    </div>
	
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav naber-right">
	        <li><a href="{% url 'appdelta:agregarclientes' %}">&nbsp;Agregar Cliente</a></li>
	        <li><a href="{% url 'appdelta:index' %}">&nbsp;Editar Cliente</a></li>
	        <li><a href="{% url 'appdelta:admin' %}">&nbsp;Administrar Cliente</a></li>
	        <li><a href="{% url 'appdelta:informacion' %}">&nbsp;Informacion general</a></li>
	        <li><a href="{% url 'appdelta:cerrarseccion' %}">&nbsp;Cerrar seccion</a></li>	        
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	
	
	{% block content %}
	{% endblock %}  
		  	   
</div>
	
</body>

</html>